#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port5,  ,               sensorVexIQ_ColorHue)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorVexIQ, openLoop, encoder)
#pragma config(Motor,  motor11,         clawMotor,     tmotorVexIQ, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//ARSHIA A KALKHORANI 106391170

void grab(){ //grab item
	motor[clawMotor] = 100;
	wait1Msec(2000);
	motor[clawMotor] = 0;
	wait1Msec(20);
}
void drop(){ //let go of item

	motor[clawMotor] = -100;

	wait1Msec(20);
}
void raise(){ //raise the arm
	motor[armMotor] = 100;
	wait1Msec(2000);
	motor[armMotor] = 0;
	wait1Msec(20);
}
void lower(){ //lower the arm
	motor[armMotor] = -100;
	wait1Msec(2000);
	motor[armMotor] = 0;
	wait1Msec(20);
}

task main()
{




	bool wayBack = false; // this is placed so we know when we are on the way back to start, so we can steer correctly
	// and also since we use sonar to



	int leftBoost = 0; // if we keep turning left more that 3 times this will boost the turning radius
	int rightBoost = 0;
	int SecondLeftBoost = 0; // if we keep turning left more that 3 times this will boost the turning radius
	int SecondRightBoost = 0;


	drop(); //opening the arm ready for pick up
	forward(3);//reach the line
	while(true){ // follow the line to the box



		if(SensorValue(colorDetector) < 200){//using all three sensors

      motor[rightMotor]=-20;		// i didn't use funtions because i hade to change the numbers a million times to get it right
			motor[leftMotor]=60;			// turn right
			rightBoost++;
			if(rightBoost == 2){//lowering this number makes the robot turn sharper     --for each two turns in a row turn extra in the same direction
				motor[rightMotor]=-80;
		   	motor[leftMotor]=60;
		   	rightBoost = 0;//reseting the var so we can use it for extra turning again
			}
			leftBoost = 0;//resting the var so we can using it for extra turning

		}
		else{


			motor[rightMotor]=60;
			motor[leftMotor]=-20;						//turn left
			leftBoost++;

			if(leftBoost == 2){//lowering this number makes the robot turn sharper     --for each two turns in a row turn extra in the same direction
				motor[rightMotor]=60;
		   	motor[leftMotor]=-80;
		   	leftBoost = 0;//resting the var so we can using it for extra turning
			}
			rightBoost = 0;//reseting the var so we can use it for extra turning again
		}
		if(SensorValue[bumpSwitch] == 0){//if touching
			motor[rightMotor]=0;	//stop
			motor[leftMotor]=0;
		  grab(); //grab the box
			raise(); // raise it up
			break;
			}
		}



	while(true){ // follow the line to the box



		if(SensorValue(colorDetector) < 200){//using all three sensors

      motor[rightMotor]=-20;		// i didn't use funtions because i hade to change the numbers a million times to get it right
			motor[leftMotor]=60;			// turn right
			rightBoost++;
			if(rightBoost == 1){//lowering this number makes the robot turn sharper     --for each two turns in a row turn extra in the same direction
				motor[rightMotor]=-80;
		   	motor[leftMotor]=60;
		   	rightBoost = 0;//reseting the var so we can use it for extra turning again
			}
			leftBoost = 0;//resting the var so we can using it for extra turning

		}
		else{


			motor[rightMotor]=60;
			motor[leftMotor]=-20;						//turn left
			leftBoost++;

			if(leftBoost == 1){//lowering this number makes the robot turn sharper     --for each two turns in a row turn extra in the same direction
				motor[rightMotor]=60;
		   	motor[leftMotor]=-80;
		   	leftBoost = 0;//resting the var so we can using it for extra turning
			}
			rightBoost = 0;//reseting the var so we can use it for extra turning again
		}
		if(SensorValue[distanceMM] > 2500){//at the end                                      //i used the distance to the end of the arena to turn right and go to start
			break;
			}
		}

		turnRight(0.7);
		forward (2.25);
		lower();
		drop();
		backward(1);


	};
